### ISSUE TITLE
Can I install on Centos with cpanel?

### ISSUE THREAD

**Issue by beserious** [mikerlynn/blacklistmonitor#16]
Hi

I am trying to install on centos with capnel... But dont know its not working. When I am trying to login, it shows blank page... could you please help on this...

**Comment by mikelynn2** [comment]
whats in /var/log/httpd/error_log

**Comment by beserious** [comment]
I get following in log

[Mon Jun 29 00:23:04 2015] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Jun 29 00:23:04 2015] [notice] Digest: generating secret for digest authentication ...
[Mon Jun 29 00:23:04 2015] [notice] Digest: done
[Mon Jun 29 00:23:04 2015] [notice] Apache/2.2.15 (Unix) DAV/2 configured -- resuming normal operations
[Mon Jun 29 01:58:00 2015] [notice] caught SIGTERM, shutting down

**Comment by beserious** [comment]
What I did is,
Uploaded the script to public_html , Created the database and made changes in blacklistmonitor.cfg... do I need to do anything else?

**Comment by mikelynn2** [comment]
i dont see any errors in that log.  But  the config script (https://github.com/mikelynn2/blacklistmonitor/blob/master/setup/blacklistmonitor.cfg)  must be installed here:
/etc/blacklistmonitor.cfg

the service script (https://github.com/mikelynn2/blacklistmonitor/blob/master/setup/blacklistmonitor.conf)  assumes its installed here:

/var/www/html/blacklistmonitor/

**Comment by rajcz** [comment]
Hi! I have problem too with Centos 7 (clear install). First is that if i add ScriptAlias directive to config, so .js and .css and .png are forbiden with errot 500 and in error log is perm. denied. Second problem is that I dont know how set service script. 
@beserious  can you send me your file servie version for centos?

**Comment by beserious** [comment]
I dont see any /etc folder in my public_html folder.... also dont have this path /var/www/html/blacklistmonitor/

please advise..

**Comment by beserious** [comment]
ok I found that path.... but showing me this error

root@host [/var/www/html]# mysql -p < /var/www/html/blacklistmonitor/setup/blacklistmonitor.sql
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

and 

root@host [/var/www/html]# cp /var/www/html/blacklistmonitor/setup/blacklistmonitor-apache.conf /etc/apache2/sites-enabled/
cp: cannot create regular file `/etc/apache2/sites-enabled/': No such file or directory

I am logged in to the root

**Comment by mikelynn2** [comment]
run it without the -p - like this:

mysql < /var/www/html/blacklistmonitor/setup/blacklistmonitor.sql

centos doesnt set a password by default on mysql.

you may also need to run this to setup a user/pass for your mysql.  So
you'd run "mysql" then run this command below with the user and pass you
want.   then restart mysql.

GRANT ALL PRIVILEGES ON blacklistmonitor.\* To
'newusername'@'localhost' IDENTIFIED BY 'password';

**Comment by rajcz** [comment]
@beserious mysql must be configured first - run mysql_secure_installation first
- you can copy it to /etc/httpd/conf.d
