### ISSUE TITLE
Is there a reason why you need to install it in /var/www/ ?

### ISSUE THREAD

**Issue by bugoff** [mikerlynn/blacklistmonitor#17]
As A sysadmin point of view i don't see any reason why you would install this script in /var/www and set the settings path to /etc/blacklist... 

To run this you require the script to run as mod-php on a box, if there would ever be a bug in the software they would have to much user rights on the system?

**Comment by mikelynn2** [comment]
Right.  I'd recommend you install in a container or its own VM/server
