### ISSUE TITLE
Init script for centos

### ISSUE THREAD

**Issue by rajcz** [mikerlynn/blacklistmonitor#19]
Hi, can you add init script for centos? Thanks!

**Comment by rajcz** [comment]
I have self-solution:-)

```
[Unit]
Description=Blacklist monitor

[Service]
Type=simple
User=root
Group=root
ExecStart=/usr/bin/php /var/www/html/blacklistmonitor/service/blacklistmonitor.php >>/var/log/blacklistmonitor.log 2>&1

# Give a reasonable amount of time for the server to start up/shut down
TimeoutSec=300

```

Save as /etc/systemd/system/blmon.service
after
systemctl restart blmon.service
systemctl stop blmon.service
systemctl start blmon.service

Apply for Centos 7 or Fedora

**Comment by mikelynn2** [comment]
@rajcz i went ahead and added this as a centos service script
