### ISSUE TITLE
sudo: sorry, you must have a tty to run sudo

### ISSUE THREAD

**Issue by amityweb** [mikerlynn/blacklistmonitor#2]
Hi

I get this error in the log:
sudo: sorry, you must have a tty to run sudo

**Comment by amityweb** [comment]
Removed the sudo -u root from blacklistmonitor.conf and now it works OK

**Comment by mikelynn2** [comment]
what ubuntu version you on?  looks related to this.  But glad you fixed it.  Mine only worked with the sudo -u root

http://unix.stackexchange.com/questions/122616/why-do-i-need-a-tty-to-run-sudo-if-i-can-sudo-without-a-password

**Comment by mikelynn2** [comment]
this answer at the bottom looks like a fix for this - will have to test to confirm

http://serverfault.com/questions/357060/how-should-i-use-sudo-from-an-upstart-script

**Comment by amityweb** [comment]
I am not on Ubuntu, but Centos. I think its working for me now.
