### ISSUE TITLE
IPs randomly going clean

### ISSUE THREAD

**Issue by cuddylier** [mikerlynn/blacklistmonitor#23]
Hi

Some of my IPs have been on multiple blacklists then suddenly they go clean then blacklisted again a few days later, why would this happen? I've also seen that a lot of IPs aren't being marked as listed on Spamhaus when they are. I use my own internal DNS servers and have the DNS lookup timeout set to 10 seconds.

**Comment by mikelynn2** [comment]
Could be a few things, if you're monitoring a lot of IPs, the RBL may not like how many times you're hitting their name server and could result in timeouts.  Its really hard to say.  Try increasing your timeout setting and add in more DNS servers to spread out the load
