### ISSUE TITLE
On a cPanel Environment

### ISSUE THREAD

**Issue by kushalraha** [mikerlynn/blacklistmonitor#24]
I have managed to install this on a cPanel / CentOS environment on a server with root access. But the automatic checks do not seem to be functioning. I believe it is something due to the service integration.

Can you please advise, what changes if any are to be made for a CentOS environment?

**Comment by mikelynn2** [comment]
i've never tried to install on CentOS - some folks here did.

https://github.com/mikelynn2/blacklistmonitor/issues/16

someone also contributed this file which does the service for centos
https://github.com/mikelynn2/blacklistmonitor/blob/master/setup/blacklistmonitor-centos-systemd.conf

So you'd do that one in place of the ubuntu service script.  looks like it has instructions in it.
