### ISSUE TITLE
PHP Warning and PHP Notice

### ISSUE THREAD

**Issue by dneto82** [mikerlynn/blacklistmonitor#26]
Info at blacklistmonitor.log

[11-Jul-2016 23:47:46 UTC] PHP Warning:  mysqli_fetch_array() expects parameter 2 to be integer, string given in /var/www/SERVERNAME/htdocs/blacklistmonitor/classes/_MySQL.class.php on line 72
[11-Jul-2016 23:47:55 UTC] PHP Notice:  Use of undefined constant MYSQL_NUM - assumed 'MYSQL_NUM' in /var/www/SERVERNAME/htdocs/blacklistmonitor/classes/_MySQL.class.php on line 72

Using PHP 7.0.8 and NGINX

**Comment by dneto82** [comment]
And cannot login with default password. :(

At nginx error logs:

`2016/07/11 20:53:09 [info] 7866#7866: *3148 client sent stream with data before settings were acknowledged while processing HTTP/2 connection, client: 10.23.80.32, server: 10.114.241.19:443
2016/07/11 20:53:09 [error] 7866#7866: *3148 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant MYSQL_ASSOC - assumed 'MYSQL_ASSOC' in /var/www/SERVERNAME/htdocs/blacklistmonitor/classes/Utilities.class.php on line 362
PHP message: PHP Warning:  mysqli_fetch_array() expects parameter 2 to be integer, string given in /var/www/SERVERNAME/htdocs/blacklistmonitor/classes/Utilities.class.php on line 362" while reading response header from upstream, client: 10.23.80.32, server: SERVERNAME.MYFQDN.COM.BR, request: "POST /blacklistmonitor/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "SERVERNAME.MYFQDN.COM.BR", referrer: "https://SERVERNAME.MYFQDN.COM.BR/blacklistmonitor/"`

**Comment by mikelynn2** [comment]
try a pull from the master now
