### ISSUE TITLE
Reset admin password

### ISSUE THREAD

**Issue by ilpops** [mikerlynn/blacklistmonitor#27]
Hello are there any steps to reset the admin password?

**Comment by ilpops** [comment]
I found my password in the password manager, just a feature request :)

**Comment by mikelynn2** [comment]
login to the system and reset it via mysql update, like this

if you set a password:
mysql -p -e "update blacklistmonitor.users set passwd = md5('pa55w0rd')"

or

if root doesnt need password:
mysql -e "update blacklistmonitor.users set passwd = md5('pa55w0rd')"
