### ISSUE TITLE
PHP 7 issue

### ISSUE THREAD

**Issue by FabioHPT** [mikerlynn/blacklistmonitor#28]
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; _FileCache has a deprecated constructor in /var/www/html/classes/blacklistmonitor/_FileCache.class.php on line 3

PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; _MeasurePerformance has a deprecated constructor in /var/www/html/classes/_MeasurePerformance.class.php on line 3

**Comment by mikelynn2** [comment]
fixed
